//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class holiday_package
    {
        public int package_code { get; set; }
        public string user_tz { get; set; }
        public string hotel_code { get; set; }
        public Nullable<int> flight_enter_code { get; set; }
        public Nullable<int> flight_back_code { get; set; }
    
        public virtual flights flights { get; set; }
        public virtual flights flights1 { get; set; }
        public virtual hotels hotels { get; set; }
        public virtual users users { get; set; }
    }
}
