//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotels
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hotels()
        {
            this.holiday_package = new HashSet<holiday_package>();
            this.room_in_hotel = new HashSet<room_in_hotel>();
        }
    
        public string hotel_code { get; set; }
        public string hotel_name { get; set; }
        public string hotel_country { get; set; }
        public string hotel_city { get; set; }
        public string hotel_address { get; set; }
        public Nullable<int> hotel_number { get; set; }
        public Nullable<int> number_of_stars { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<holiday_package> holiday_package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_in_hotel> room_in_hotel { get; set; }
    }
}
