//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class travel_agentEntities : DbContext
    {
        public travel_agentEntities()
            : base("name=travel_agentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<flights> flights { get; set; }
        public virtual DbSet<holiday_package> holiday_package { get; set; }
        public virtual DbSet<hotels> hotels { get; set; }
        public virtual DbSet<room_in_hotel> room_in_hotel { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<country> country { get; set; }
    }
}
