//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_in_hotel
    {
        public int room_number { get; set; }
        public string hotel_code { get; set; }
        public Nullable<int> number_of_beds { get; set; }
        public Nullable<int> room_price { get; set; }
    
        public virtual hotels hotels { get; set; }
    }
}
