 delete from country where countryId>661
 select * from country
 insert into COUNTRY (countryKey,countryDisplayName) values ('AUH','Abu Dabi')
 insert into COUNTRY (countryKey,countryDisplayName) values ('Eg','Abu Dabi')

 update country set countryKey='AHO' where countryId=591

INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DZA','Algeria')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ASM','American Samoa')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AND','Andorra')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AGO','Angola')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AIA','Anguilla')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ATA','Antarctica')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ATG','Antigua and Barbuda')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ARG','Argentina')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ARM','Armenia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ABW','Aruba')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AUS','Australia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AUT','Austria')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' AZE','Azerbaijan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BHS','Bahamas')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BHR','Bahrain')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BGD','Bangladesh')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BRB','Barbados')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BLR','Belarus')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BEL','Belgium')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BLZ','Belize')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BEN','Benin')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BMU','Bermuda')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BTN','Bhutan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BOL','Bolivia, Plurinational State of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BOL','Bolivia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BIH','Bosnia and Herzegovina')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BWA','Botswana')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BVT','Bouvet Island')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BRA','Brazil')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IOT','British Indian Ocean Territory')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BRN','Brunei Darussalam')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BRN','Brunei')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BGR','Bulgaria')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BFA','Burkina Faso')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' BDI','Burundi')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KHM','Cambodia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CMR','Cameroon')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CAN','Canada')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CPV','Cape Verde')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CYM','Cayman Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CAF','Central African Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TCD','Chad')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CHL','Chile')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CHN','China')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CXR','Christmas Island')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CCK','Cocos (Keeling) Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CO','Colombia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' COM','Comoros')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' COG','Congo')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' COD','Congo, the Democratic Republic of the')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' COK','Cook Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CRI','Costa Rica')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CIV','Ivory Coast')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HRV','Croatia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CUB','Cuba')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CYP','Cyprus')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CZE','Czech Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DNK','Denmark')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DJI','Djibouti')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DMA','Dominica')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DOM','Dominican Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ECU','Ecuador')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' EGY','Egypt')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SLV','El Salvador')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GNQ','Equatorial Guinea')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ERI','Eritrea')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GLP','Guadeloupe')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GUM','Guam')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GTM','Guatemala')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GGY','Guernsey')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GIN','Guinea')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GNB','Guinea-Bissau')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GUY','Guyana')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HTI','Haiti')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HMD','Heard Island and McDonald Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VAT','Holy See (Vatican City State)')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HND','Honduras')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HKG','Hong Kong')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' HUN','Hungary')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ISL','Iceland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IND','India')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IDN','Indonesia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IRN','Iran, Islamic Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IRQ','Iraq')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IRL','Ireland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' IMN','Isle of Man')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ISR','Israel')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ITA','Italy')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' JAM','Jamaica')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' JPN','Japan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PLW','Palau')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PSE','Palestinian Territory, Occupied')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PAN','Panama')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PNG','Papua New Guinea')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PRY','Paraguay')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PER','Peru')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PHL','Philippines')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PCN','Pitcairn')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' POL','Poland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PRT','Portugal')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PRI','Puerto Rico')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' QAT','Qatar')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ROU','Romania')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' RUS','Russian Federation')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' RUS','Russia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' RWA','Rwanda')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SHN','Saint Helena, Ascension and Tristan da Cunha')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KNA','Saint Kitts and Nevis')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LCA','Saint Lucia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SPM','Saint Pierre and Miquelon')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VCT','Saint Vincent and the Grenadines')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VCT','Saint Vincent & the Grenadines')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TUR','Turkey')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TKM','Turkmenistan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TCA','Turks and Caicos Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TUV','Tuvalu')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' UGA','Uganda')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' UKR','Ukraine')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ARE','United Arab Emirates')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GBR','United Kingdom')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' USA','United States')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' UMI','United States Minor Outlying Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' URY','Uruguay')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' UZB','Uzbekistan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VUT','Vanuatu')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VEN','Venezuela, Bolivarian Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VEN','Venezuela')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VNM','Viet Nam')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VNM','Vietnam')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VGB','Virgin Islands, British')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VIR','Virgin Islands, U.S.')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' WLF','Wallis and Futuna')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ESH','Western Sahara')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' YEM','Yemen')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ZMB','Zambia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ZWE','Zimbabwe')



INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' EST','Estonia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ETH','Ethiopia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' FRO','Faroe Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' FJI','Fiji')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' FIN','Finland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' "FRA','France')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' "GUF','French Guiana')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' "PYF','French Polynesia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' "ATF','French Southern Territories')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES('GAB','Gabon')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GMB','Gambia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GEO','Georgia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' DEU','Germany')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GHA','Ghana')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GIB','Gibraltar')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GRC','Greece')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GRL','Greenland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' GRD','Grenada')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES('JEY','Jersey')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' JOR','Jordan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KAZ','Kazakhstan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KEN','Kenya')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KIR','Kiribati')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PRK','Korea, Democratic Peoples Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KOR','Korea, Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KOR','South Korea')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KWT','Kuwait')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' KGZ','Kyrgyzstan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LAO','Lao Peoples Democratic Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LVA','Latvia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LBN','Lebanon')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LSO','Lesotho')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LBR','Liberia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LBY','Libyan Arab Jamahiriya')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LBY','Libya')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LIE','Liechtenstein')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LTU','Lithuania')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LUX','Luxembourg')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MAC','Macao')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MKD','Macedonia, the former Yugoslav Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MDG','Madagascar')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MWI','Malawi')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MYS','Malaysia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MDV','Maldives')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MLI','Mali')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MLT','Malta')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MHL','Marshall Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MTQ','Martinique')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MRT','Mauritania')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MUS','Mauritius')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MYT','Mayotte')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MEX','Mexico')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' FSM','Micronesia, Federated States of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MDA','Moldova, Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MCO','Monaco')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MNG','Mongolia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MNE','Montenegro')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MSR','Montserrat')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MAR','Morocco')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MOZ','Mozambique')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MMR','Myanmar')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MMR','Burma')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NAM','Namibia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NRU','Nauru')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NPL','Nepal')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NLD','Netherlands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ANT','Netherlands Antilles')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NCL','New Caledonia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NZL','New Zealand')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NIC','Nicaragua')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NER','Niger')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NGA','Nigeria')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NIU','Niue')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NFK','Norfolk Island')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' MNP','Northern Mariana Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' NOR','Norway')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' OMN','Oman')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' PAK','Pakistan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' VCT','Saint Vincent and the Grenadines')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' WSM','Samoa')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SMR','San Marino')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' STP','Sao Tome and Principe')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SAU','Saudi Arabia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SEN','Senegal')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SRB','Serbia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SYC','Seychelles')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SLE','Sierra Leone')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SGP','Singapore')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SVK','Slovakia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SVN','Slovenia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SLB','Solomon Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SOM','Somalia')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ZAF','South Africa')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SGS','South Georgia and the South Sandwich Islands')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SSD','South Sudan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' ESP','Spain')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' LKA','Sri Lanka')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SDN','Sudan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SUR','Suriname')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SJM','Svalbard and Jan Mayen')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SWZ','Swaziland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SWE','Sweden')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' CHE','Switzerland')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' SYR','Syrian Arab Republic')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TWN','Taiwan, Province of China')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TWN','Taiwan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TJK','Tajikistan')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TZA','Tanzania, United Republic of')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' THA','Thailand')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TLS','Timor-Leste')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TGO','Togo')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TKL','Tokelau')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TON','Tonga')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TTO','Trinidad and Tobago')
INSERT INTO COUNTRY (countryKey,countryDisplayName) VALUES(' TUN','Tunisia')




